package com.itdept.timetable.controller;

import com.itdept.timetable.model.*;
import com.itdept.timetable.service.TimetableGenerationService;


import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;

import jakarta.servlet.ServletOutputStream;
import jakarta.servlet.http.HttpServletResponse;



import lombok.RequiredArgsConstructor;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Exports the GA-generated timetable as a unified HTML page
 * matching the original IT dept PDF format exactly:
 *   - All 3 years (2IT/3IT/4IT) in ONE grid per day
 *   - Short break column between slot 2 and 3
 *   - Lunch break column between slot 4 and 5
 *   - Saturday: slots 1-4 only (09:00–13:10), slots 5-6 greyed out
 *   - Lab batches (I1/I2/I3) shown in one cell
 *   - Theory: code + faculty shortCode + room
 */
@RestController
@RequestMapping("/api/timetable")
@RequiredArgsConstructor
public class TimetableExportController {
	@Autowired
	private TimetableGenerationService timetableService;

    private final TimetableGenerationService generationService;

    private static final String[] DAYS  = {"MON","TUE","WED","THU","FRI","SAT"};
    private static final String[] SLOT_LABELS = {
        "09:00–10:00","10:00–11:00","11:10–12:10",
        "12:10–13:10","14:00–15:00","15:00–16:00"
    };
    private static final String[] YEARS = {"SE","TE","BE"};
    private static final String[] YEAR_LABELS = {"2IT (SE)","3IT (TE)","4IT (BE)"};
    @GetMapping("/{id}/export/pdf")
    public void exportPdf(@PathVariable Long id, HttpServletResponse response) throws Exception {

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=timetable.pdf");

        String html = "<html><body><h1>PDF WORKING</h1></body></html>"; // test first

        PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.withHtmlContent(html, null);
        builder.toStream(response.getOutputStream());
        builder.run();
    }

    // ─── Build the full HTML ────────────────────────────────────────────────

    private String buildUnifiedHtml(TimetableVersion version, List<TimetableSlot> allSlots) {

        // Index slots: grid[year][day][slot] = list of TimetableSlot
        // year: "SE","TE","BE"  day: "MON"…"SAT"  slot: 1-6
        Map<String, Map<String, Map<Integer, List<TimetableSlot>>>> grid = new LinkedHashMap<>();
        for (String y : YEARS) {
            grid.put(y, new LinkedHashMap<>());
            for (String d : DAYS) {
                grid.get(y).put(d, new LinkedHashMap<>());
                for (int s = 1; s <= 6; s++) grid.get(y).get(d).put(s, new ArrayList<>());
            }
        }
        for (TimetableSlot ts : allSlots) {
            String yr  = ts.getYearClass().name();
            String day = ts.getDay().name();
            int    sl  = ts.getSlotNumber();
            if (grid.containsKey(yr) && grid.get(yr).containsKey(day) && sl >= 1 && sl <= 6) {
                grid.get(yr).get(day).get(sl).add(ts);
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.append(htmlHead(version));

        // ── Header ──
        sb.append("<div class='college'>P.D.E.A's College of Engineering, Manjari (Bk'), Pune</div>");
        sb.append("<div class='tt-title'>TIME TABLE &nbsp;—&nbsp; Master Time Table</div>");
        sb.append("<div class='meta'>");
        sb.append("<span><b>Academic Year:</b> ").append(version.getAcademicYear()).append("</span>");
        sb.append("<span><b>Department:</b> INFORMATION TECHNOLOGY</span>");
        sb.append("<span><b>Semester-II</b> &nbsp; with Effect from: 05/01/2026</span>");
        sb.append("<span style='color:#10B981'><b>Generated by GA</b> &nbsp; ").append(
            LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"))).append("</span>");
        sb.append("</div>");

        // ── Main table ──
        sb.append("<table><thead><tr>");
        sb.append("<th class='hdr col-day'>DAY</th>");
        sb.append("<th class='hdr col-cls'>Class</th>");
        for (int s = 1; s <= 6; s++) {
            if (s == 3) sb.append("<th class='hdr col-brk'>").append(breakLabel("SHORT")).append("</th>");
            if (s == 5) sb.append("<th class='hdr col-brk'>").append(breakLabel("LUNCH")).append("</th>");
            sb.append("<th class='hdr col-slot'>").append(s)
              .append("<br><span class='sub'>").append(SLOT_LABELS[s-1]).append("</span></th>");
        }
        sb.append("</tr></thead><tbody>");

        // ── Days ──
        for (String day : DAYS) {
            boolean isSat = day.equals("SAT");

            // SAT: re-emit compact header showing 09:00–13:10 only
            if (isSat) {
                sb.append("<tr class='sat-hdr'>");
                sb.append("<td class='hdr' colspan='2'>SAT</td>");
                sb.append("<td class='hdr col-slot'>1<br><span class='sub'>09:00–10:00</span></td>");
                sb.append("<td class='hdr col-slot'>2<br><span class='sub'>10:00–11:00</span></td>");
                sb.append("<td class='hdr col-brk'>").append(breakLabel("SHORT")).append("</td>");
                sb.append("<td class='hdr col-slot'>3<br><span class='sub'>11:10–12:10</span></td>");
                sb.append("<td class='hdr col-slot'>4<br><span class='sub'>12:10–13:10</span></td>");
                sb.append("<td class='hdr sat-off' colspan='3'>No classes after 13:10</td>");
                sb.append("</tr>");
            }

            for (int yi = 0; yi < YEARS.length; yi++) {
                String year      = YEARS[yi];
                String yearLabel = YEAR_LABELS[yi];

                sb.append("<tr>");

                // Day label (rowspan=3, first year only)
                if (yi == 0 && !isSat) {
                    sb.append("<td class='day-label' rowspan='3'>").append(day).append("</td>");
                } else if (yi == 0 && isSat) {
                    sb.append("<td class='day-label' rowspan='3'>SAT</td>");
                }

                // Class label
                sb.append("<td class='cls-label'>").append(yearLabel).append("</td>");

                // Slots 1-6 with break columns
                for (int s = 1; s <= 6; s++) {
                    if (s == 3 && yi == 0) sb.append("<td class='break-v' rowspan='3'>S<br>H<br>O<br>R<br>T<br><br>B<br>R<br>E<br>A<br>K</td>");
                    if (s == 5 && yi == 0 && !isSat) sb.append("<td class='break-v' rowspan='3'>L<br>U<br>N<br>C<br>H<br><br>B<br>R<br>E<br>A<br>K</td>");

                    // SAT: slots 5 and 6 → greyed out spanning all years
                    if (isSat && s == 5 && yi == 0) {
                        sb.append("<td class='sat-off' colspan='3' rowspan='3'>—</td>");
                        break;
                    }
                    if (isSat && s > 4) break;

                    List<TimetableSlot> cells = grid.get(year).get(day).get(s);
                    sb.append(renderCell(cells, day, s, isSat));
                }

                sb.append("</tr>");
            }

            // Day separator
            sb.append("<tr class='day-sep'><td colspan='10'></td></tr>");
        }

        sb.append("</tbody></table>");

        // ── Subject Legend ──
        sb.append(buildLegend(allSlots));

        // ── Footer ──
        sb.append("<div class='footer'>");
        sb.append("<div class='fi'><div class='fn'>Prof. Shalu Saraswat</div><div class='fr'>Time Table I/C</div></div>");
        sb.append("<div class='fi'><div class='fn'>Dr. D. S. Hirolikar</div><div class='fr'>HOD</div></div>");
        sb.append("<div class='fi'><div class='fn'>Dr. S. A. Patil</div><div class='fr'>Academic I/C</div></div>");
        sb.append("<div class='fi'><div class='fn'>Dr. R. V. Patil</div><div class='fr'>Principal</div></div>");
        sb.append("</div>");

        sb.append("</body></html>");
        return sb.toString();
    }

    // ─── Render one table cell ──────────────────────────────────────────────

    private String renderCell(List<TimetableSlot> slots, String day, int slotNum, boolean isSat) {
        if (slots.isEmpty()) {
            return "<td class='empty'>—</td>";
        }

        // Group by division: null = theory, "I1"/"I2"/"I3" = lab
        boolean hasLab    = slots.stream().anyMatch(TimetableSlot::isLabSession);
        boolean hasTheory = slots.stream().anyMatch(s -> !s.isLabSession());

        // Lab batches in one cell
        if (hasLab && !hasTheory) {
            // Sort by division I1 < I2 < I3
            List<TimetableSlot> labs = slots.stream()
                .filter(TimetableSlot::isLabSession)
                .sorted(Comparator.comparing(s -> s.getDivision() == null ? "" : s.getDivision()))
                .collect(Collectors.toList());

            StringBuilder sb = new StringBuilder("<td class='lab-cell'>");
            for (TimetableSlot ts : labs) {
                sb.append("<div class='lab-row'>")
                  .append("<span class='batch'>").append(ts.getDivision() != null ? ts.getDivision() : "").append("</span>")
                  .append(" – <b>").append(ts.getCourse().getCode()).append("</b>")
                  .append(" (").append(roomTypeShort(ts.getRoom().getType())).append(")")
                  .append(" – ").append(ts.getFaculty().getShortCode())
                  .append("</div>");
            }
            sb.append("</td>");
            return sb.toString();
        }

        // Theory session (should be only one per cell if GA is conflict-free)
        if (hasTheory && !hasLab) {
            TimetableSlot ts = slots.stream().filter(s -> !s.isLabSession()).findFirst().get();
            // Special cells
            if (ts.getCourse().getCode().equalsIgnoreCase("INTERN") ||
                ts.getCourse().getCode().equalsIgnoreCase("INTERNSHIP")) {
                return "<td class='special-cell'>Internship</td>";
            }
            if (ts.getCourse().getCode().equalsIgnoreCase("AUDBE") ||
                ts.getCourse().getCode().equalsIgnoreCase("AUDTE")) {
                return "<td class='theory-cell'><div class='code'>Audit</div>" +
                       "<div class='staff'>" + ts.getFaculty().getShortCode() + "</div>" +
                       "<div class='room'>" + ts.getRoom().getName() + "</div></td>";
            }
            if (ts.getCourse().getCode().equalsIgnoreCase("TPOBE") ||
                ts.getCourse().getCode().equalsIgnoreCase("TPO")) {
                return "<td class='special-cell'>TPO<div class='staff'>" +
                       ts.getFaculty().getShortCode() + "</div></td>";
            }
            if (ts.getCourse().getCode().equalsIgnoreCase("PROJECT")) {
                return "<td class='project-cell'><div class='pcode'>PROJECT WORK</div>" +
                       "<div class='pstaff'>Project Lab</div>" +
                       "<div class='pstaff'>DSH, ABG, RMK, SS, SJ</div></td>";
            }
            return "<td class='theory-cell'>" +
                   "<div class='code'>" + ts.getCourse().getCode() + "</div>" +
                   "<div class='staff'>" + ts.getFaculty().getShortCode() + "</div>" +
                   "<div class='room'>" + ts.getRoom().getName() + "</div></td>";
        }

        // Mixed (conflict) — highlight in red
        StringBuilder sb = new StringBuilder("<td class='conflict-cell'>");
        for (TimetableSlot ts : slots) {
            sb.append("<div class='conf-row'>").append(ts.getCourse().getCode())
              .append("/").append(ts.getFaculty().getShortCode()).append("</div>");
        }
        sb.append("</td>");
        return sb.toString();
    }

    private String roomTypeShort(Room.RoomType type) {
        return switch (type) {
            case SOFTWARE_LAB -> "SW Lab";
            case LINUX_LAB    -> "Linux Lab";
            case PROJECT_LAB  -> "Proj Lab";
            case CLASSROOM    -> "Room";
        };
    }

    private String breakLabel(String type) {
        return "<span style='writing-mode:vertical-lr;text-orientation:mixed;" +
               "transform:rotate(180deg);font-size:8px;color:#555'>" + type + " BREAK</span>";
    }

    // ─── Subject legend ─────────────────────────────────────────────────────

    private String buildLegend(List<TimetableSlot> allSlots) {
        Map<String, Map<String, String>> byYear = new LinkedHashMap<>();
        for (String y : YEARS) byYear.put(y, new LinkedHashMap<>());

        for (TimetableSlot ts : allSlots) {
            String yr   = ts.getYearClass().name();
            String code = ts.getCourse().getCode();
            String val  = ts.getCourse().getFullName() + " — " + ts.getFaculty().getName();
            byYear.get(yr).putIfAbsent(code, val);
        }

        StringBuilder sb = new StringBuilder("<div class='legend'><table style='width:100%;border-collapse:collapse'><tr>");
        String[] titles = {"SE (2IT) – Second Year", "TE (3IT) – Third Year", "BE (4IT) – Final Year"};

        for (int i = 0; i < YEARS.length; i++) {
            String yr = YEARS[i];
            sb.append("<td style='vertical-align:top;padding:0 8px;border-right:1px solid #ddd'>");
            sb.append("<strong>").append(titles[i]).append("</strong><br>");
            for (Map.Entry<String, String> e : byYear.get(yr).entrySet()) {
                boolean isLab = allSlots.stream().anyMatch(s ->
                    s.getYearClass().name().equals(yr) &&
                    s.getCourse().getCode().equals(e.getKey()) &&
                    s.isLabSession());
                sb.append("<span class='leg-dot ").append(isLab ? "lab" : "theory").append("'>■</span>")
                  .append(" <b>").append(e.getKey()).append("</b>")
                  .append(" – ").append(e.getValue()).append("<br>");
            }
            sb.append("</td>");
        }
        sb.append("</tr></table></div>");
        return sb.toString();
    }

    // ─── HTML head with all CSS ─────────────────────────────────────────────

    private String htmlHead(TimetableVersion version) {

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <title>Master Timetable – IT Dept """ 
        + version.getAcademicYear() + " Sem-" + version.getSemester() + """
        </title>

        <style>
          *{box-sizing:border-box;margin:0;padding:0}
          body{font-family:Arial,sans-serif;font-size:10.5px;background:#fff;color:#111;padding:12px}

          .college{text-align:center;font-size:14px;font-weight:bold;text-transform:uppercase;letter-spacing:1px;margin-bottom:2px}
          .tt-title{text-align:center;font-size:12px;font-weight:bold;margin-bottom:4px}
          .meta{display:flex;justify-content:space-between;flex-wrap:wrap;gap:4px;font-size:10px;
                font-weight:bold;border-top:2px solid #111;border-bottom:1px solid #555;
                padding:3px 6px;margin-bottom:6px}

          table{width:100%;border-collapse:collapse;table-layout:fixed}
          th,td{border:1px solid #666;padding:3px 3px;vertical-align:middle;text-align:center;
                font-size:9.5px;line-height:1.3}

          .col-day{width:26px} 
          .col-cls{width:44px} 
          .col-slot{width:108px} 
          .col-brk{width:22px}

          .hdr{background:#1a1a2e;color:#fff;font-weight:bold;font-size:9px}
          .hdr .sub{font-size:8px;font-weight:normal;color:#bbb}
          .sat-hdr td{font-size:9px}
          .sat-off{background:#f0f0f0;color:#aaa;font-style:italic;font-size:9px}

          .day-label{background:#1a1a2e;color:#fff;font-weight:bold;font-size:11px;
                     padding:4px 2px}

          .cls-label{background:#f3f4f6;font-weight:bold;font-size:9.5px;text-align:center}

          .break-v{background:#e5e7eb;color:#666;font-size:7px;
                   padding:3px 1px;width:22px}

          .day-sep td{height:3px;background:#333;border:none;padding:0}

          /* Theory */
          .theory-cell{background:#eef2ff;border-left:3px solid #4361ee;text-align:left;padding:3px 4px}
          .theory-cell .code{font-weight:bold;font-size:11px;color:#1a1a2e}
          .theory-cell .staff{font-size:8.5px;color:#4361ee}
          .theory-cell .room{font-size:8px;color:#666}

          /* Lab */
          .lab-cell{background:#f0fdf4;text-align:left;padding:3px 4px}
          .lab-row{font-size:9px;line-height:1.55;color:#1a1a2e}
          .lab-row .batch{font-weight:bold;color:#166534}

          /* Special */
          .special-cell{background:#fffbeb;font-weight:bold;font-size:9.5px;color:#92400e}
          .project-cell{background:#fdf4ff}
          .project-cell .pcode{font-weight:bold;font-size:10px;color:#7e22ce}
          .project-cell .pstaff{font-size:8px;color:#666}

          .empty{background:#fafafa;color:#ccc}
          .conflict-cell{background:#fee2e2;border-left:3px solid #ef4444}
          .conf-row{font-size:8px;color:#dc2626;font-weight:bold}

          /* Legend */
          .legend{margin-top:10px;padding:8px;background:#f9fafb;
                  border:1px solid #e5e7eb;border-radius:4px;font-size:9px;line-height:1.7}

          .leg-dot.theory{color:#4361ee} 
          .leg-dot.lab{color:#166534}

          /* Footer */
          .footer{display:flex;justify-content:space-around;margin-top:10px;
                  padding-top:6px;border-top:1px solid #555;font-size:9.5px}

          .fi{text-align:center} 
          .fn{font-weight:bold} 
          .fr{color:#666}

        </style>
        </head>
        <body>
        """;
    }
}